In [1]:
import pandas as pd

In [2]:
visitation_df = pd.read_csv("./Resources/Annual_Visitation.csv")
visitation_df.head()

,Park Name,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Average
0,Acadia National Park,2504208.0,2374645.0,2431052.0,2254922.0,2563129.0,2811184.0,3303393.0,3509271,3537575,3437286,2872667
1,Arches National Park,1014405.0,1040758.0,1070577.0,1082866.0,1284767.0,1399247.0,1585718.0,1539028,1663557,1659702,1334063
2,Badlands National Park,977778.0,870741.0,883406.0,892372.0,868094.0,989354.0,996263.0,1054325,1008942,970998,951227
3,Big Bend National Park,372330.0,361862.0,292055.0,316953.0,314102.0,381747.0,388290.0,440276,440091,463832,377154
4,Biscayne National Park,467612.0,476077.0,495613.0,486848.0,525745.0,508164.0,514709.0,446961,469253,708522,509950

In [3]:
parks_df = pd.read_csv("./Resources/parks.csv")
parks_df.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

In [4]:
species_df = pd.read_csv("./Resources/species.csv")

species_df.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN

In [12]:
for col in species_df.columns:
    print(col)

Species ID
Park Name
Category
Order
Family
Scientific Name
Common Names
Record Status
Occurrence
Nativeness
Abundance
Seasonality
Conservation Status

In [7]:
join_df = species_df.merge(parks_df, left_index=True, right_index=True)
join_df= join_df.drop(['Park Name_y'], axis=1)
join_df.head()

,Species ID,Park Name_x,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,ACAD,ME,47390,44.35,-68.21
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,ARCH,UT,76519,38.68,-109.57
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,BADL,SD,242756,43.75,-102.50
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,BIBE,TX,801163,29.25,-103.25
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,BISC,FL,172924,25.65,-80.08

In [10]:
join_df = join_df.merge(visitation_df, left_index=True, right_index=True)
join_df= join_df.drop(['Park Name_x'], axis=1)
join_df.head()

,Species ID,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,...,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y,2019_y,Average_y
0,ACAD-1000,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,...,2374645.0,2431052.0,2254922.0,2563129.0,2811184.0,3303393.0,3509271,3537575,3437286,2872667
1,ACAD-1001,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,...,1040758.0,1070577.0,1082866.0,1284767.0,1399247.0,1585718.0,1539028,1663557,1659702,1334063
2,ACAD-1002,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,...,870741.0,883406.0,892372.0,868094.0,989354.0,996263.0,1054325,1008942,970998,951227
3,ACAD-1003,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,...,361862.0,292055.0,316953.0,314102.0,381747.0,388290.0,440276,440091,463832,377154
4,ACAD-1004,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,...,476077.0,495613.0,486848.0,525745.0,508164.0,514709.0,446961,469253,708522,509950

In [11]:
for col in join_df.columns:
    print(col)

Species ID
Category
Order
Family
Scientific Name
Common Names
Record Status
Occurrence
Nativeness
Abundance
Seasonality
Conservation Status
Park Code
State
Acres
Latitude
Longitude
2010_x
2011_x
2012_x
2013_x
2014_x
2015_x
2016_x
2017_x
2018_x
2019_x
Average_x
Park Name_y
2010_y
2011_y
2012_y
2013_y
2014_y
2015_y
2016_y
2017_y
2018_y
2019_y
Average_y

In [16]:
join_df.to_csv('joined_df.csv', index=False)